spring:
  application:
    name: bike-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ----------------------------
# 개발 환경(dev) 설정
# ----------------------------
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.h2.Driver
    # H2 인메모리 DB URL (H2 콘솔과 맞추기 위해 testdb 사용)
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    # 스키마 생성 후에 data.sql 스크립트 실행
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: abcdefghijklmnsdfghnkuwbnvuijbvouiwbowuouvouwrbouoopqrstuvwxyz123456

server:
  port: 8080

logging:
  level:
    "[root]": INFO
    "[org.springframework]": INFO

naver:
  api:
    key:
      id: 8hvd3r358o
      key: PBi1PFpwL0H9PJgM2boBh3hHG7jAO0v8WzwXPgo8
